### ISSUE TITLE
Definição do nome e logo da equipe

### ISSUE THREAD

**Issue by omadson** [atlantico-academy/equipe9-2024.3#1]
Esta é a primeira atividade de equipe e tem como objetivo a construção de uma proto-identidade visual (nome e logomarca) para cada equipe. Vocês poderão discutir e escolher o nome e logomarca nesse canal. A logomarca e nome serão utilizados posteriormente nas capas de repositório, slides e na composição de aplicações e relatórios da equipe.

Para executar esta tarefa, cada equipe deve primeiro discutir sobre o nome no grupo do discord. Pode ser realizado um _brainstorm_ para criação de uma lista inicial. Cada integrante pode sugerir dois nomes nessa etapa.

Com a primeira lista em mãos, os integrantes podem escolher seus favoritos. Essa etapa pode ser realizada através de uma votação, em que cada integrante pode escolher dois nomes que não foram sua sugestão.

Ao fim desta etapa, uma lista dos dois nomes mais votados pode ser elencada e então pode ser efetuada uma nova rodada de votação, neste caso sem a restrição de voto do criador do nome. O nome mais votado será o escolhido.

**Nota**
- Além do nome, é interessante uma explicação do motivo da sua escolha.
- É interessante usar nomes que "facilitem" a criação da logomarca.

A criação da logo pode ser efetuada após a escolha do nome por algum participante (ou mesmo vários) com maior habilidade com ferramentas gráficas. Se necessário, também pode ser realizada uma votação para escolha da logo.

**Comment by Rwalam** [comment]
done
